### PR TITLE
Align: code to documentation

### PR DESCRIPTION
**Pull request by lesyk**

### CODE REVIEW

**Comment by KillianKemps** [comment]
Thank you lesyk for your PR. Can you tell me for what reason do you need the script to update parent directories?

The usage I had when doing this script was to go to my development folder and launch the script with `./update`.
What I understand you propose is to go to `my-development-folder/Git-Repo-Update` and then `./repo-update.sh`. Which is a little bit longer.

This is just a detail for this script, but as it changes radically the behaviour for those who are using it, I would like to understand what is the added value of your proposition. ;)

**Comment by lesyk** [comment]
According to your documentation:

> Installation
> In your folder containing all git repositories to update:
> `ln -s Git-Repo-Update/repo-update.sh update`

You do not say that script itself should be copied anywhere.

Also, I think it is better not to copy script anywhere, but store it inside folder together with git stuff, since, users will have ability to update script without additional operations.

User story:
1. git clone repo
2. create symlink
3. run ./update from Workspace -> script will update everything including script

What do you think?

**Comment by KillianKemps** [comment]
Sorry for the little delay for answering to your message.
Actually I think what you are telling is exactly what I meant 😃. I understand that the Readme I wrote wasn't very clear.

So, I've updated the Readme to make it a little bit clearer. Please tell me if it's better according to you : https://github.com/KillianKemps/Git-Repo-Update

**Comment by lesyk** [comment]
Good. Thx.

**Pull request closed without merging**
